### PR TITLE
[FEAT] Add LQ approximation functionality

### PR DESCRIPTION
**Pull request by QBatista**
First step for addressing #31

### CODE REVIEW

**Comment by oyamad** [comment]
@QBatista Thanks!
The error seems to be this one jump-dev/MutableArithmetics.jl#91.
Let's wait for the latest version of `MutableArithmetics.jl` to be released.

**Comment by oscardssmith** [comment]
Any chance of a point release for the library so precompilation can be fixed?

**Comment by oyamad** [comment]
@oscardssmith Thank you for your interest in this library.

But I suspect you meant to leave a comment for `MutableArithmetics.jl`, possibly at jump-dev/MutableArithmetics.jl#93?

**Comment by odow** [comment]
I released a new version.

**Comment by oscardssmith** [comment]
Thanks!

**Pull request merged**
